version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:9.0
    container_name: moneymesh-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banking_system
      MYSQL_USER: moneymesh
      MYSQL_PASSWORD: moneymesh123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mvp_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - moneymesh-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: moneymesh-backend
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: moneymesh
      SPRING_DATASOURCE_PASSWORD: moneymesh123
      JWT_SECRET: your-256-bit-secret-key-change-in-production
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - moneymesh-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moneymesh-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - moneymesh-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  moneymesh-network:
    driver: bridge
